# Generated by Django 6.0.3 on 2026-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pcategory', models.CharField(max_length=50)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='11.webp', upload_to='uploads/')),
            ],
        ),
    ]
